
package facultad.tse.practico.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentosSOAPService", targetNamespace = "http://ws.practico.tse.facultad/", wsdlLocation = "http://localhost:8080/practico-web/DocumentosSOAP?wsdl")
public class DocumentosSOAPService
    extends Service
{

    private final static URL DOCUMENTOSSOAPSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTOSSOAPSERVICE_EXCEPTION;
    private final static QName DOCUMENTOSSOAPSERVICE_QNAME = new QName("http://ws.practico.tse.facultad/", "DocumentosSOAPService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/practico-web/DocumentosSOAP?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOCUMENTOSSOAPSERVICE_WSDL_LOCATION = url;
        DOCUMENTOSSOAPSERVICE_EXCEPTION = e;
    }

    public DocumentosSOAPService() {
        super(__getWsdlLocation(), DOCUMENTOSSOAPSERVICE_QNAME);
    }

    public DocumentosSOAPService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTOSSOAPSERVICE_QNAME, features);
    }

    public DocumentosSOAPService(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTOSSOAPSERVICE_QNAME);
    }

    public DocumentosSOAPService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTOSSOAPSERVICE_QNAME, features);
    }

    public DocumentosSOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentosSOAPService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentosSOAP
     */
    @WebEndpoint(name = "DocumentosSOAPPort")
    public DocumentosSOAP getDocumentosSOAPPort() {
        return super.getPort(new QName("http://ws.practico.tse.facultad/", "DocumentosSOAPPort"), DocumentosSOAP.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentosSOAP
     */
    @WebEndpoint(name = "DocumentosSOAPPort")
    public DocumentosSOAP getDocumentosSOAPPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.practico.tse.facultad/", "DocumentosSOAPPort"), DocumentosSOAP.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOCUMENTOSSOAPSERVICE_EXCEPTION!= null) {
            throw DOCUMENTOSSOAPSERVICE_EXCEPTION;
        }
        return DOCUMENTOSSOAPSERVICE_WSDL_LOCATION;
    }

}
