
package facultad.tse.practico.ws;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentosSOAP", targetNamespace = "http://ws.practico.tse.facultad/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentosSOAP {


    /**
     * 
     * @param arg0
     * @return
     *     returns facultad.tse.practico.ws.Documento
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarPorId", targetNamespace = "http://ws.practico.tse.facultad/", className = "facultad.tse.practico.ws.BuscarPorId")
    @ResponseWrapper(localName = "buscarPorIdResponse", targetNamespace = "http://ws.practico.tse.facultad/", className = "facultad.tse.practico.ws.BuscarPorIdResponse")
    public Documento buscarPorId(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<facultad.tse.practico.ws.Documento>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listar", targetNamespace = "http://ws.practico.tse.facultad/", className = "facultad.tse.practico.ws.Listar")
    @ResponseWrapper(localName = "listarResponse", targetNamespace = "http://ws.practico.tse.facultad/", className = "facultad.tse.practico.ws.ListarResponse")
    public List<Documento> listar();

    /**
     * 
     * @param arg0
     * @return
     *     returns facultad.tse.practico.ws.Documento
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buscarPorPaciente", targetNamespace = "http://ws.practico.tse.facultad/", className = "facultad.tse.practico.ws.BuscarPorPaciente")
    @ResponseWrapper(localName = "buscarPorPacienteResponse", targetNamespace = "http://ws.practico.tse.facultad/", className = "facultad.tse.practico.ws.BuscarPorPacienteResponse")
    public Documento buscarPorPaciente(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "agregar", targetNamespace = "http://ws.practico.tse.facultad/", className = "facultad.tse.practico.ws.Agregar")
    @ResponseWrapper(localName = "agregarResponse", targetNamespace = "http://ws.practico.tse.facultad/", className = "facultad.tse.practico.ws.AgregarResponse")
    public void agregar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
